### ISSUE TITLE
Cloudfront logs parsing issues

### ISSUE THREAD

**Issue by bonclay7** [DataDog/dd-aws-lambda-functions#48]
Hi !

I've tried to setup the logs fowarder function to parse Cloudfront logs. I used an S3 trigger according to the documentation (manual triggering).

After the setup, the logs were perfectly forwarded by with an `s3 source`. I figured that you look the keyword `cloudfront` in the s3 filename. 

https://github.com/DataDog/dd-aws-lambda-functions/blob/master/Log/lambda_function.py#L295-L296

My workaround was to add the keyword `cloudfront` into the prefix on cloudfront logging and it worked fine. Could you update to documentation to make it more clear ?

**Comment by tmichelet** [comment]
Hi @bonclay7 thanks for reporting, we will be having a look and reach back

**Comment by NBParis** [comment]
Hello @bonclay7.

This is actually already in the documentation (https://cl.ly/d709c666bfec) but could be better highlighted.

We will make sure to improve the display on this article (https://docs.datadoghq.com/integrations/amazon_cloudfront/#enable-cloudfront-logging).

Thanks for letting us know.

**Comment by bonclay7** [comment]
Thanks !

**Comment by markusgulden** [comment]
I disagree, documentation is far from clear what to do, actually the sentence `specify cloudfront as prefix for the file names, to keep track of which log files are associated with which distributions.` doesn't make sense.
And the documentation hasn't been improved since 2018, obviously.

Unfortunately, this is just another example how bad the DataDog documentation is, and that you sometimes have to find your solution in a five year-old GH issue.

Thanks to the thread opener for this solution.

**Comment by NilsBunge** [comment]
Hello @markusgulden , 

We added it as **Important Note** at the top of the log collection section of the cloudfront integration document:
<img width="802" alt="image" src="https://github.com/DataDog/datadog-serverless-functions/assets/26930812/5b5e05ba-a77d-4a4f-b2c6-d4027e86f9a9">

Do you believe a specific FAQ article targeting this specific problem would help to better find it? Happy to get your suggestions on how we could make it more visible.

**Comment by markusgulden** [comment]
Yes, but this not is misleading:

> Store the log files for multiple distributions in the same bucket

This sounds like it is mandatory, and if it wouldn't work if I do it otherwise. I have a dedicated bucket per distribution, and that is not an issue (same bucket for all distributions would be additional effort in our multi-account setup)

> specify `cloudfront` as prefix for the file names, to keep track which log files are associated with which distributions

Sorry, but I still don't understand the meaning of that sentence. 
It should be more like "use `cloudfront` as prefix, so DataDog can auto-categorize the logs as CloudFront logs"

**Comment by NilsBunge** [comment]
Made some updates based on the suggestion to reflect this which should be live soon.

Let us know what you think and thanks helping us improve our documentation.
